In [2]:
import aocd
puzzle = aocd.get_puzzle(year=2024, day=2)

In [3]:
puzzle.examples[0].input_data

'7 6 4 2 1\n1 2 7 8 9\n9 7 6 2 1\n1 3 2 4 5\n8 6 4 4 1\n1 3 6 7 9'

In [22]:
import numpy as np
def parse_reports(input_data):
    return [np.array([int(number) for number in line.split()]) for line in input_data.splitlines() if line]

parse_reports(puzzle.examples[0].input_data)

[array([7, 6, 4, 2, 1]),
 array([1, 2, 7, 8, 9]),
 array([9, 7, 6, 2, 1]),
 array([1, 3, 2, 4, 5]),
 array([8, 6, 4, 4, 1]),
 array([1, 3, 6, 7, 9])]

In [23]:
def is_report_safe(report):
    diffs = np.diff(report, axis=-1)
    diffs_same_sign = np.all(diffs > 0, axis=-1) | np.all(diffs < 0, axis=-1)
    diffs_correct_magnitude = np.all((np.abs(diffs) >= 1) & (np.abs(diffs) <= 3), axis=-1)

    return diffs_same_sign & diffs_correct_magnitude

def num_safe_reports(reports):
    return np.sum([np.sum(is_report_safe(report)) for report in reports])

In [24]:
for example in puzzle.examples:
    report = parse_reports(example.input_data)
    print(report)
    print(is_report_safe(report))
    print(f"Safe Reports: {num_safe_reports(report)=} - {example.answer_a=}")

[array([7, 6, 4, 2, 1]), array([1, 2, 7, 8, 9]), array([9, 7, 6, 2, 1]), array([1, 3, 2, 4, 5]), array([8, 6, 4, 4, 1]), array([1, 3, 6, 7, 9])]
[ True False False False False  True]
Safe Reports: num_safe_reports(report)=np.int64(2) - example.answer_a='2'


In [25]:
aocd.submit(num_safe_reports(parse_reports(puzzle.input_data)), part='a', year=2024, day=2)

coerced int64 value np.int64(598) for 2024/02 to '598'


That's the right answer!  You are one gold star closer to finding the Chief Historian. [Continue to Part Two]
