In [3]:
import aocd
puzzle = aocd.get_puzzle(year=2024, day=2)

In [4]:
puzzle.examples[0].input_data

'7 6 4 2 1\n1 2 7 8 9\n9 7 6 2 1\n1 3 2 4 5\n8 6 4 4 1\n1 3 6 7 9'

In [5]:
import numpy as np
def parse_reports(input_data):
    return [np.array([int(number) for number in line.split()]) for line in input_data.splitlines() if line]

parse_reports(puzzle.examples[0].input_data)

[array([7, 6, 4, 2, 1]),
 array([1, 2, 7, 8, 9]),
 array([9, 7, 6, 2, 1]),
 array([1, 3, 2, 4, 5]),
 array([8, 6, 4, 4, 1]),
 array([1, 3, 6, 7, 9])]

In [20]:
def is_report_safe(report):
    diffs = np.diff(report, axis=-1)
    diffs_same_sign = np.all(diffs > 0, axis=-1) | np.all(diffs < 0, axis=-1)
    diffs_correct_magnitude = np.all((np.abs(diffs) >= 1) & (np.abs(diffs) <= 3), axis=-1)

    return diffs_same_sign & diffs_correct_magnitude

def num_safe_reports(reports):
    return np.sum([np.sum(is_report_safe(report)) for report in reports])

In [7]:
for example in puzzle.examples:
    report = parse_reports(example.input_data)
    print(report)
    print(is_report_safe(report))
    print(f"Safe Reports: {num_safe_reports(report)=} - {example.answer_a=}")

[array([7, 6, 4, 2, 1]), array([1, 2, 7, 8, 9]), array([9, 7, 6, 2, 1]), array([1, 3, 2, 4, 5]), array([8, 6, 4, 4, 1]), array([1, 3, 6, 7, 9])]
[ True False False False False  True]
Safe Reports: num_safe_reports(report)=np.int64(2) - example.answer_a='2'


In [8]:
aocd.submit(num_safe_reports(parse_reports(puzzle.input_data)), part='a', year=2024, day=2)

coerced int64 value np.int64(598) for 2024/02 to '598'


Part a already solved with same answer: 598


In [50]:
def is_report_safe_tolerate(report):
    candidates = np.stack(
        [np.delete(report, ix) for ix in range(len(report))],
        axis=0,
    )

    return is_report_safe(candidates)


def num_safe_reports_tolerate(reports):
    return sum(int(is_report_safe_tolerate(report)) for report in reports)

In [46]:
for example in puzzle.examples:
    report = parse_reports(example.input_data)
    print(report)
    print([is_report_safe_tolerate(r) for r in report])
    print(f"Safe Reports: {num_safe_reports_tolerate(report)=} - {example.answer_b=}")

[array([7, 6, 4, 2, 1]), array([1, 2, 7, 8, 9]), array([9, 7, 6, 2, 1]), array([1, 3, 2, 4, 5]), array([8, 6, 4, 4, 1]), array([1, 3, 6, 7, 9])]
[False, False, False, False, False, False]
Safe Reports: num_safe_reports_tolerate(report)=0 - example.answer_b='4'


In [43]:
aocd.submit(num_safe_reports_tolerate(parse_reports(puzzle.input_data)), part='b', year=2024, day=2)

wrong answer: That's not the right answer; your answer is too low.  If you're stuck, make sure you're using the full input data; there are also some general tips on the about page, or you can ask for hints on the subreddit.  Please wait one minute before trying again. [Return to Day 2]


That's not the right answer; your answer is too low.  If you're stuck, make sure you're using the full input data; there are also some general tips on the about page, or you can ask for hints on the subreddit.  Please wait one minute before trying again. [Return to Day 2]


In [49]:
num_safe_reports_tolerate(parse_reports(puzzle.input_data))

623